---
language: node_js

node_js:
  - 6.11
  
addons:
  chrome: stable

install: 
  - npm install

script: 
  - npm test

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: test-sikse-pou-nou-tout